user nginx;

worker_processes auto;

events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;

    default_type application/octet-stream;

    server {
        listen 80;

        server_name _;

        root /usr/share/nginx/html;

        index index.html;

        # Serve the frontend
        location / {
            try_files $uri $uri/ =404;
        }

        # Forward API requests to the internal Application Load Balancer
        location /api/ {
            proxy_pass http://internal-GUVI-Internal-ALB-1856288662.ap-south-1.elb.amazonaws.com:5000/; ##Need to be updated to new DNS

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}
